# Generated by Django 4.2.25 on 2025-12-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketsapp', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reporter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
